version: "3.8"
services:
  redis:
    image: bitnami/redis:6.2.12
    ports:
      - 6379:6379
    volumes:
      - ./redis-persistence:/redis/data
    networks:
      - chatbot
    environment:
      # - REDIS_DISABLE_COMMANDS=CONFIG
      - REDIS_PASSWORD=chatbot
      - REDIS_PORT_NUMBER=6379
    container_name: redis_chatbot
  dev-db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot2023
      POSTGRES_DB: chatbot
    networks:
      - chatbot
    container_name: postgres_chatbot
  app:
    depends_on:
      - redis
      - dev-db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot_app
    restart: on-failure
    ports:
      - 80:80
    networks:
      - chatbot
    env_file:
      - .env
networks:
  chatbot:
